import java.util.*;
class MyClass {
    
    private static void append(List<String> contextTokens, String matchingTrigger, String leftOfTitle,String rightOfTitle, StringBuilder sb) {
        boolean printedTitle = false;
        for (int i=0; i<contextTokens.size(); i++) {
            if (contextTokens.get(i).equals(matchingTrigger)) {
                continue;
            }
            if (sb.length() > 0) {
                sb.append(" ");
            }
            if (!printedTitle && rightOfTitle != null && contextTokens.get(i).equals(rightOfTitle)) {
                sb.append("-TITLE- ");
                printedTitle = true;
            }
            sb.append(contextTokens.get(i));
            if (!printedTitle && leftOfTitle != null && contextTokens.get(i).equals(leftOfTitle)) {
                sb.append(" -TITLE-");
                printedTitle = true;
            }
        }
        if (!printedTitle) {
            sb.append(" -TITLE-");
        }
    }
    private static boolean idfHigher(String matchingTrigger, String token, String[] triggers) {
        int matchingIdfIndex = -1;
        int tokenIdfIndex = -1;
        for (int i=0; i<triggers.length; i++) {
            if (triggers[i].equals(matchingTrigger)) {
                matchingIdfIndex = i;
            }
            if (triggers[i].equals(token)) {
                tokenIdfIndex = i;
            }
        }
        if (matchingIdfIndex == -1 || tokenIdfIndex == -1) {
            return false;
        }
        return matchingIdfIndex < tokenIdfIndex; // triggers are in asc IDF
    }
    public static void context_pruning(String[] contexts, String[] triggers) {
        for (String context : contexts) {
            String matchingTrigger = null;
            boolean matchedTokenOnLeftSide = true;
            String leftOfTitle = null;
            String rightOfTitle = null;
            List<String> contextTokens = new ArrayList<String>();
            List<String> tokensSinceMatchingToken = new ArrayList<String>();
            boolean foundTitle = false;
            for (String token : context.split(" ")) {
                if (token.equals("-TITLE-")) {
                    foundTitle = true;
                    if (matchingTrigger == null) {
                        contextTokens.clear();
                    }
                    continue;
                }
                //
                if (!foundTitle) {
                    leftOfTitle = token;
                } else if (rightOfTitle == null) {
                    rightOfTitle = token;
                }
                //
                for (String trigger : triggers) {
                    if (token.equals(trigger) && (matchingTrigger == null || idfHigher(matchingTrigger, token, triggers))) {
                        matchingTrigger = token;
                        if (foundTitle) {
                            matchedTokenOnLeftSide = false;
                        } else {
                            contextTokens.clear();
                            matchedTokenOnLeftSide = true;
                        }
                        for (String t : tokensSinceMatchingToken) {
                            if (contextTokens.indexOf(t) == -1) {
                                contextTokens.add(t);
                            }
                        }
                        tokensSinceMatchingToken.clear();
                    } else if ((matchingTrigger == null || !foundTitle) && !token.equals(matchingTrigger)) {
                        if (contextTokens.indexOf(token) == -1) {
                            contextTokens.add(token);
                        }
                    } else if (matchingTrigger != null && !token.equals(matchingTrigger) && tokensSinceMatchingToken.indexOf(token) == -1) {
                        tokensSinceMatchingToken.add(token);
                    }
                }
            }
            if (matchingTrigger == null) {
                // ignore 
                continue;
            }
            StringBuilder sb = new StringBuilder();
            if (matchedTokenOnLeftSide) {
                sb.append(matchingTrigger);
                append(contextTokens, matchingTrigger, leftOfTitle, rightOfTitle, sb);

                if (rightOfTitle != null) {
                    sb.append(" " + rightOfTitle);
                }
            } else {
                if (leftOfTitle != null) {
                    sb.append(leftOfTitle);
                }
                append(contextTokens, matchingTrigger, leftOfTitle, rightOfTitle, sb);

                sb.append(" " + matchingTrigger);


            }
            //System.out.println("matchingTrigger " + matchingTrigger + ", left " + matchedTokenOnLeftSide + ", Context '" + context + "': '" + sb + "', contextTokens " + contextTokens);
            System.out.println(sb);
        }
        
    }
    public static void main(String[] args) {
        String[] contexts = new String[] {
"-TITLE- The birch canoe",
		"dark blue background -TITLE- ",
		"juice -TITLE- of lemons makes",
		"of steady work -TITLE- faced us",
		"A -TITLE- large size in",
		"there when the -TITLE- sun rose",
		"flame and heat -TITLE- ",
		"The salt breeze -TITLE- came across from",
		"fish -TITLE- twisted and turned",
		"the pants and -TITLE- sew a button",
		"beauty -TITLE- of the view",
		"in the tank -TITLE- ",
		"of useless trash -TITLE- ",
		"and threw the -TITLE- tall rider",
		"It -TITLE- snowed, rained, and",
		"Take the winding -TITLE- path to reach",
		"birth to kittens -TITLE- ",
		"What joy there -TITLE- is in living",
		"king ruled the -TITLE- state in the",
		"Sickness -TITLE- kept him home",
		"the hot sun -TITLE- ",
		"The lazy cow -TITLE- lay in the",
		"the -TITLE- square stone over",
		"The -TITLE- rope will bind",
		"and plunge in -TITLE- ",
		"the drug store -TITLE- ",
		"Mesh -TITLE- wire keeps chicks",
		"a flop from -TITLE- the very start",
		"saw is a -TITLE- tool used for",
		"the next hill -TITLE- ",
		"Both -TITLE- lost their lives",
		"in the circus -TITLE- ",
		"write the first -TITLE- draft",
		"to the hardware -TITLE- store",
		"small creek cut -TITLE- across the field",
		"stalled in snow -TITLE- drifts",
		"hit the floor -TITLE- with a crash",
		"words were the -TITLE- cue for the",
		"slid around the -TITLE- point into the",
		"met while playing -TITLE- on the sand",
		"on the finished -TITLE- page",
		"A -TITLE- tame squirrel makes",
		"with firm strokes -TITLE- ",
		"pearl -TITLE- was worn in",
		"See -TITLE- the cat glaring",
		"to lose his -TITLE- case",
		"around the fence -TITLE- post",
		"pie into large -TITLE- parts",
		"lay deep along -TITLE- the street",
		"the blue air -TITLE- ",
		"cut the clear -TITLE- water",
		"play seems dull -TITLE- and quite stupid",
		"to stop it -TITLE- from sinking",
		"ended in late -TITLE- june that year",
		"used to make -TITLE- costly gifts",
		"were set in -TITLE- order",
		"bill -TITLE- was paid every",
		" -TITLE- The birch canoe",
		"dark blue background -TITLE- ",
		"juice -TITLE- of lemons makes",
		"corn and garbage -TITLE- ",
		"hard to sell -TITLE- ",
		"is used to -TITLE- catch pink salmon",
		"to her feet -TITLE- ",
		"from the sea -TITLE- ",
		"the booth sold -TITLE- fifty bonds",
		"the -TITLE- pants and sew",
		"Her purse was -TITLE- full of useless",
		"verse out loud -TITLE- for pleasure",
		"your left shoulder -TITLE- ",
		"the -TITLE- winding path to",
		"the -TITLE- coat before you",
		"The -TITLE- wrist was badly",
		"birth to kittens -TITLE- ",
		"A -TITLE- king ruled the",
		"ship was torn -TITLE- apart on the",
		"the third week -TITLE- ",
		"lazy cow lay -TITLE- in the cool",
		"over the fence -TITLE- ",
		"seven books at -TITLE- once",
		"left the drug -TITLE- store",
		"keeps chicks inside -TITLE- ",
		"was a flop -TITLE- from the very",
		"past the next -TITLE- hill",
		"the porch steps -TITLE- ",
		"show in the -TITLE- circus",
		"Use -TITLE- a pencil to",
		"ran -TITLE- half way to",
		"struck to mark -TITLE- the third period",
		"A small creek -TITLE- cut across the",
		"stalled in snow -TITLE- drifts",
		"with a crash -TITLE- ",
		"playing on the -TITLE- sand",
		"in sixteen weeks -TITLE- ",
		"Navy attacked the -TITLE- big task force",
		"the -TITLE- cat glaring at",
		"There -TITLE- are more than",
		"hat brim was -TITLE- wide and too",
		"lose his case -TITLE- ",
		"The -TITLE- grass curled around",
		"moved a limb -TITLE- ",
		"The slush lay -TITLE- deep along the",
		"the blue air -TITLE- ",
		"sugar costs more -TITLE- than eggs",
		"the clear water -TITLE- ",
		"dull and quite -TITLE- stupid",
		" -TITLE- The birch canoe",
		"dark blue background -TITLE- ",
		"tell the depth -TITLE- of a well",
		"a rare dish -TITLE- ",
		"Rice is often -TITLE- served in round",
		"the parked truck -TITLE- ",
		"rod is used -TITLE- to catch pink",
		"the woman get -TITLE- back to her",
		"Smoky -TITLE- fires lack flame",
		"small -TITLE- pup gnawed a",
		"and turned on -TITLE- the bent hook",
		"on the vest -TITLE- ",
		"swan dive was -TITLE- far short of",
		"you go out -TITLE- ",
		"was badly strained -TITLE- and hung limp",
		"cat gave birth -TITLE- to kittens",
		"young girl gave -TITLE- no clear response",
		"lay in the -TITLE- cool grass",
		"rope will bind -TITLE- the seven books",
		"leads to wrong -TITLE- sums",
		"The show was -TITLE- a flop from",
		"The wagon moved -TITLE- on well oiled",
		"ran -TITLE- half way to",
		"Cars and busses -TITLE- stalled in snow",
		"china hit the -TITLE- floor with a",
		"grand season for -TITLE- hikes on the",
		"seized without a -TITLE- fight",
		"a nice pet -TITLE- ",
		"and with firm -TITLE- strokes",
		"pearl was worn -TITLE- in a thin",
		"cut in thick -TITLE- slices",
		"the big task -TITLE- force",
		"glaring at the -TITLE- scared mouse",
		"hat brim was -TITLE- wide and too",
		"into large parts -TITLE- ",
		"seldom get rich -TITLE- ",
		"along the street -TITLE- ",
		"hung in the -TITLE- blue air",
		"sugar costs more -TITLE- than eggs",
		"The fin was -TITLE- sharp and cut",
		" -TITLE- The birch canoe",
		"dark blue background -TITLE- ",
		"in round bowls -TITLE- ",
		"box -TITLE- was thrown beside",
		"work faced us -TITLE- ",
		"the sun rose -TITLE- ",
		"and follow through -TITLE- ",
		"lack flame and -TITLE- heat",
		"from the sea -TITLE- ",
		"Press the pants -TITLE- and sew a",
		"far short of -TITLE- perfect",
		"in the tank -TITLE- ",
		"purse was full -TITLE- of useless trash",
		"Read -TITLE- verse out loud",
		"and hung limp -TITLE- ",
		"young -TITLE- girl gave no",
		"What -TITLE- joy there is",
		"ruled the state -TITLE- in the early",
		"the hot sun -TITLE- ",
		"the square stone -TITLE- over the fence",
		"rope -TITLE- will bind the",
		"and plunge in -TITLE- ",
		"The -TITLE- frosty air passed",
		"The -TITLE- crooked maze failed",
		"used for making -TITLE- boards",
		"wagon moved on -TITLE- well oiled wheels",
		"the next hill -TITLE- ",
		"the porch steps -TITLE- ",
		"in the raging -TITLE- storm",
		"talked of the -TITLE- side show in",
		"He -TITLE- ran half way",
		"clock -TITLE- struck to mark",
		"small creek cut -TITLE- across the field",
		"grand season for -TITLE- hikes on the",
		"met while playing -TITLE- on the sand",
		"walled -TITLE- town was seized",
		"horn -TITLE- of the car",
		"The -TITLE- pearl was worn",
		"was cut in -TITLE- thick slices",
		"the scared mouse -TITLE- ",
		"The -TITLE- hat brim was",
		"strive but seldom -TITLE- get rich",
		"close -TITLE- the barn door",
		"fin was sharp -TITLE- and cut the",
		"The -TITLE- play seems dull",
		"the -TITLE- boat to stop",
		"term ended in -TITLE- late june that",
		"were set in -TITLE- order",
		" -TITLE- The birch canoe",
		"dark blue background -TITLE- ",
		"is a rare -TITLE- dish",
		"Rice is often -TITLE- served in round",
		"were fed chopped -TITLE- corn and garbage",
		"hours of steady -TITLE- work faced us",
		"hard to sell -TITLE- ",
		"source -TITLE- of the huge",
		"straight and follow -TITLE- through",
		"A pot of -TITLE- tea helps to",
		"flame and heat -TITLE- ",
		"soft cushion broke -TITLE- the man's fall",
		"salt breeze came -TITLE- across from the",
		"on the bent -TITLE- hook",
		"pants and sew -TITLE- a button on",
		"far short of -TITLE- perfect",
		"colt reared and -TITLE- threw the tall",
		"It snowed, rained, -TITLE- and hailed the",
		"your left shoulder -TITLE- ",
		"reach the lake -TITLE- ",
		"closely -TITLE- the size of",
		"no clear response -TITLE- ",
		"was cooked before -TITLE- the bell rang",
		"What -TITLE- joy there is",
		"ship -TITLE- was torn apart",
		"the hot sun -TITLE- ",
		"lazy -TITLE- cow lay in",
		"over the fence -TITLE- ",
		"the fence and -TITLE- plunge in",
		"gang left the -TITLE- drug store",
		"Mesh -TITLE- wire keeps chicks",
		"The -TITLE- frosty air passed",
		"The crooked maze -TITLE- failed to fool",
		"used for making -TITLE- boards",
		"the raging storm -TITLE- ",
		"of the side -TITLE- show in the",
		"pencil to write -TITLE- the first draft",
		"the hardware store -TITLE- ",
		"mark the third -TITLE- period",
		"small -TITLE- creek cut across",
		"busses stalled in -TITLE- snow drifts",
		"with a crash -TITLE- ",
		"was seized without -TITLE- a fight",
		"A tame squirrel -TITLE- makes a nice",
		"and with firm -TITLE- strokes",
		"cut in thick -TITLE- slices",
		"The Navy attacked -TITLE- the big task",
		"was wide and -TITLE- too droopy",
		"deep along the -TITLE- street",
		"dull and quite -TITLE- stupid",
		"term -TITLE- ended in late",
		"bill -TITLE- was paid every",
		" -TITLE- The birch canoe",
		"dark blue background -TITLE- ",
		"box -TITLE- was thrown beside",
		"hours -TITLE- of steady work",
		"the -TITLE- ball straight and",
		"pot -TITLE- of tea helps",
		"small -TITLE- pup gnawed a",
		"on the vest -TITLE- ",
		"the view stunned -TITLE- the young boy",
		"blue -TITLE- fish swam in",
		"of useless trash -TITLE- ",
		"the -TITLE- coat before you",
		"The -TITLE- wrist was badly",
		"stray -TITLE- cat gave birth",
		"on the sharp -TITLE- reef",
		"Sickness kept him -TITLE- home the third",
		"road shimmered in -TITLE- the hot sun",
		"in the cool -TITLE- grass",
		"the -TITLE- square stone over",
		"the drug store -TITLE- ",
		"keeps chicks inside -TITLE- ",
		"through the coat -TITLE- ",
		"show was a -TITLE- flop from the",
		"The -TITLE- wagon moved on",
		"their lives in -TITLE- the raging storm",
		"We talked of -TITLE- the side show",
		"a -TITLE- pencil to write",
		"The clock struck -TITLE- to mark the",
		"is -TITLE- a grand season",
		"dried on the -TITLE- finished page",
		"The -TITLE- walled town was",
		"peel was cut -TITLE- in thick slices",
		"Navy -TITLE- attacked the big",
		"glaring at the -TITLE- scared mouse",
		"than two factors -TITLE- here",
		"hat brim was -TITLE- wide and too",
		"The -TITLE- lawyer tried to",
		"grass curled around -TITLE- the fence post",
		"seldom get rich -TITLE- ",
		"Always -TITLE- close the barn",
		"deep along the -TITLE- street",
		"wisp -TITLE- of cloud hung",
		"more than eggs -TITLE- ",
		"The -TITLE- bill was paid",
		" -TITLE- The birch canoe",
		"dark blue background -TITLE- ",
		"to tell the -TITLE- depth of a",
		"days -TITLE- a chicken leg",
		"Rice -TITLE- is often served",
		"box was thrown -TITLE- beside the parked",
		"hours of steady -TITLE- work faced us",
		"the sun rose -TITLE- ",
		"source of the -TITLE- huge river is",
		"Kick -TITLE- the ball straight",
		"the -TITLE- woman get back",
		"in the sock -TITLE- ",
		"Press -TITLE- the pants and",
		"The beauty of -TITLE- the view stunned",
		"fish swam in -TITLE- the tank",
		"colt -TITLE- reared and threw",
		"Read -TITLE- verse out loud",
		"badly strained and -TITLE- hung limp",
		"young girl gave -TITLE- no clear response",
		"meal -TITLE- was cooked before",
		"What joy there -TITLE- is in living",
		"the state in -TITLE- the early days",
		"apart on the -TITLE- sharp reef",
		"home the third -TITLE- week",
		"the square stone -TITLE- over the fence",
		"Hop -TITLE- over the fence",
		"friendly gang left -TITLE- the drug store",
		"wire keeps chicks -TITLE- inside",
		"tool used for -TITLE- making boards",
		"moved on well -TITLE- oiled wheels",
		"of sugar makes -TITLE- sweet fudge",
		"the first draft -TITLE- ",
		"ran -TITLE- half way to",
		"across the field -TITLE- ",
		"set -TITLE- of china hit",
		"This -TITLE- is a grand",
		"dune -TITLE- rose from the",
		"were the cue -TITLE- for the actor",
		"around the point -TITLE- into the bay",
		"heart -TITLE- beat strongly and",
		"cut in thick -TITLE- slices",
		"attacked the big -TITLE- task force",
		"than two factors -TITLE- here",
		"Men -TITLE- strive but seldom",
		"the barn door -TITLE- tight",
		"He -TITLE- lay prone and",
		"the clear water -TITLE- ",
		"seems dull and -TITLE- quite stupid",
		"stop it from -TITLE- sinking",
		"to make costly -TITLE- gifts",
		"Ten pins were -TITLE- set in order",
		" -TITLE- The birch canoe",
		"dark blue background -TITLE- ",
		"to tell the -TITLE- depth of a",
		"served in round -TITLE- bowls",
		"makes fine punch -TITLE- ",
		"box -TITLE- was thrown beside",
		"work faced us -TITLE- ",
		"hard to sell -TITLE- ",
		"boy -TITLE- was there when",
		"A pot of -TITLE- tea helps to",
		"breeze came across -TITLE- from the sea",
		"sold fifty bonds -TITLE- ",
		"The small pup -TITLE- gnawed a hole",
		"blue -TITLE- fish swam in",
		"the tall rider -TITLE- ",
		"snowed, rained, and -TITLE- hailed the same",
		"verse out loud -TITLE- for pleasure",
		"Hoist -TITLE- the load to",
		"size of the -TITLE- gas tank",
		"coat before you -TITLE- go out",
		"The young girl -TITLE- gave no clear",
		"cooked before the -TITLE- bell rang",
		"the sharp reef -TITLE- ",
		"cow lay in -TITLE- the cool grass",
		"friendly gang left -TITLE- the drug store",
		"frosty air passed -TITLE- through the coat",
		"The -TITLE- crooked maze failed",
		"Adding fast leads -TITLE- to wrong sums",
		"the very start -TITLE- ",
		"tool used for -TITLE- making boards",
		"wagon moved on -TITLE- well oiled wheels",
		"cup of sugar -TITLE- makes sweet fudge",
		"Place -TITLE- a rosebush near",
		"their lives in -TITLE- the raging storm",
		"the side show -TITLE- in the circus",
		"Use a pencil -TITLE- to write the",
		"Cars -TITLE- and busses stalled",
		"A yacht slid -TITLE- around the point",
		"lease -TITLE- ran out in",
		"heart -TITLE- beat strongly and",
		"fruit -TITLE- peel was cut",
		"big task force -TITLE- ",
		"more than two -TITLE- factors here",
		"lay prone and -TITLE- hardly moved a",
		"and quite stupid -TITLE- ",
		"the -TITLE- boat to stop",
		"A -TITLE- Tusk is used",
		"bill -TITLE- was paid every",
		" -TITLE- The birch canoe",
		"dark blue background -TITLE- ",
		"box was thrown -TITLE- beside the parked",
		"corn and garbage -TITLE- ",
		"hours of steady -TITLE- work faced us",
		"there when the -TITLE- sun rose",
		"is used to -TITLE- catch pink salmon",
		"the huge river -TITLE- is the clear",
		"straight and follow -TITLE- through",
		"the woman get -TITLE- back to her",
		"pot of tea -TITLE- helps to pass",
		"breeze came across -TITLE- from the sea",
		"at the booth -TITLE- sold fifty bonds",
		"short of perfect -TITLE- ",
		"view stunned the -TITLE- young boy",
		"fish swam in -TITLE- the tank",
		"was full of -TITLE- useless trash",
		"loud for pleasure -TITLE- ",
		"Hoist -TITLE- the load to",
		"Take -TITLE- the winding path",
		"closely the size -TITLE- of the gas",
		"Wipe the grease -TITLE- off his dirty",
		"strained and hung -TITLE- limp",
		"stray cat gave -TITLE- birth to kittens",
		"What joy there -TITLE- is in living",
		"the early days -TITLE- ",
		"wide -TITLE- road shimmered in",
		"failed to fool -TITLE- the mouse",
		"Adding -TITLE- fast leads to",
		"A saw is -TITLE- a tool used",
		"the porch steps -TITLE- ",
		"the raging storm -TITLE- ",
		"We talked of -TITLE- the side show",
		"pencil to write -TITLE- the first draft",
		"He ran half -TITLE- way to the",
		"The -TITLE- clock struck to",
		"across the field -TITLE- ",
		"stalled in snow -TITLE- drifts",
		"on the road -TITLE- ",
		"The -TITLE- dune rose from",
		"Those words were -TITLE- the cue for",
		"tame squirrel makes -TITLE- a nice pet",
		"heart beat strongly -TITLE- and with firm",
		"The fruit peel -TITLE- was cut in",
		"The Navy attacked -TITLE- the big task",
		"but seldom get -TITLE- rich",
		"barn door tight -TITLE- ",
		"prone and hardly -TITLE- moved a limb",
		"lay deep along -TITLE- the street",
		"hung in the -TITLE- blue air",
		"pound -TITLE- of sugar costs",
		"it from sinking -TITLE- ",
		"Tusk -TITLE- is used to",
		"set in order -TITLE- ",
		" -TITLE- The birch canoe",
		"dark blue background -TITLE- ",
		"easy -TITLE- to tell the",
		"is often served -TITLE- in round bowls",
		"The juice of -TITLE- lemons makes fine",
		"the parked truck -TITLE- ",
		"The hogs were -TITLE- fed chopped corn",
		"steady work faced -TITLE- us",
		"large -TITLE- size in stockings",
		"the clear spring -TITLE- ",
		"ball straight and -TITLE- follow through",
		"the woman get -TITLE- back to her",
		"flame and heat -TITLE- ",
		"The salt breeze -TITLE- came across from",
		"girl at the -TITLE- booth sold fifty",
		"a hole in -TITLE- the sock",
		"turned on the -TITLE- bent hook",
		"Press the pants -TITLE- and sew a",
		"The swan dive -TITLE- was far short",
		"colt -TITLE- reared and threw",
		"snowed, -TITLE- rained, and hailed",
		"Read -TITLE- verse out loud",
		"the gas tank -TITLE- ",
		"no clear response -TITLE- ",
		"What -TITLE- joy there is",
		"the state in -TITLE- the early days",
		"on the sharp -TITLE- reef",
		"stone over the -TITLE- fence",
		"keeps chicks inside -TITLE- ",
		"Place -TITLE- a rosebush near",
		"lost -TITLE- their lives in",
		"talked of the -TITLE- side show in",
		"a pencil to -TITLE- write the first",
		"Cars and busses -TITLE- stalled in snow",
		"dune rose from -TITLE- the edge of",
		"were the cue -TITLE- for the actor",
		"while playing on -TITLE- the sand",
		"The ink stain -TITLE- dried on the",
		"hat brim was -TITLE- wide and too",
		"The lawyer tried -TITLE- to lose his",
		"the pie into -TITLE- large parts",
		"strive -TITLE- but seldom get",
		"of cloud hung -TITLE- in the blue",
		"The play seems -TITLE- dull and quite",
		"stop it from -TITLE- sinking",
		"june that year -TITLE- ",
		"to make costly -TITLE- gifts",
		"were set in -TITLE- order",
		"bill -TITLE- was paid every",
		" -TITLE- The birch canoe",
		"dark blue background -TITLE- ",
		"chicken leg is -TITLE- a rare dish",
		"work faced us -TITLE- ",
		"The boy was -TITLE- there when the",
		"fires -TITLE- lack flame and",
		"from the sea -TITLE- ",
		"booth sold fifty -TITLE- bonds",
		"on the bent -TITLE- hook",
		"Press -TITLE- the pants and",
		"dive was far -TITLE- short of perfect",
		"in the tank -TITLE- ",
		"Her purse was -TITLE- full of useless",
		"and threw the -TITLE- tall rider",
		"hailed the same -TITLE- morning",
		"to your left -TITLE- shoulder",
		"the gas tank -TITLE- ",
		"his dirty face -TITLE- ",
		"The -TITLE- meal was cooked",
		"What joy there -TITLE- is in living",
		"the state in -TITLE- the early days",
		"on the sharp -TITLE- reef",
		"home the third -TITLE- week",
		"Hop -TITLE- over the fence",
		"left the drug -TITLE- store",
		"frosty air passed -TITLE- through the coat",
		"Adding -TITLE- fast leads to",
		"The -TITLE- show was a",
		"on well oiled -TITLE- wheels",
		"a rosebush near -TITLE- the porch steps",
		"in the circus -TITLE- ",
		"The -TITLE- clock struck to",
		"creek cut across -TITLE- the field",
		"in snow drifts -TITLE- ",
		"cue for the -TITLE- actor to leave",
		"yacht -TITLE- slid around the",
		"The walled town -TITLE- was seized without",
		"out in sixteen -TITLE- weeks",
		"woke the sleeping -TITLE- cop",
		"was worn in -TITLE- a thin silver",
		"at the scared -TITLE- mouse",
		"hat -TITLE- brim was wide",
		"to lose his -TITLE- case",
		"around the fence -TITLE- post",
		"the barn door -TITLE- tight",
		"lay prone and -TITLE- hardly moved a",
		"sugar costs more -TITLE- than eggs",
		" -TITLE- The birch canoe",
		"dark blue background -TITLE- ",
		"It's easy to -TITLE- tell the depth",
		"chicken leg is -TITLE- a rare dish",
		"lemons makes fine -TITLE- punch",
		"The hogs were -TITLE- fed chopped corn",
		"The source of -TITLE- the huge river",
		"Kick -TITLE- the ball straight",
		"to her feet -TITLE- ",
		"Smoky -TITLE- fires lack flame",
		"from the sea -TITLE- ",
		"sold fifty bonds -TITLE- ",
		"gnawed a hole -TITLE- in the sock",
		"sew a button -TITLE- on the vest",
		"Two -TITLE- blue fish swam",
		"purse was full -TITLE- of useless trash",
		"out loud for -TITLE- pleasure",
		"grease off his -TITLE- dirty face",
		"before you go -TITLE- out",
		"The -TITLE- wrist was badly",
		"birth to kittens -TITLE- ",
		"What -TITLE- joy there is",
		"the third week -TITLE- ",
		"The -TITLE- wide road shimmered",
		"the cool grass -TITLE- ",
		"over the fence -TITLE- ",
		"Mesh -TITLE- wire keeps chicks",
		"crooked maze failed -TITLE- to fool the",
		"saw -TITLE- is a tool",
		"past the next -TITLE- hill",
		"a rosebush near -TITLE- the porch steps",
		"A small creek -TITLE- cut across the",
		"and busses stalled -TITLE- in snow drifts",
		"a grand season -TITLE- for hikes on",
		"words were the -TITLE- cue for the",
		"The -TITLE- walled town was",
		"horn of the -TITLE- car woke the",
		"a thin silver -TITLE- ring",
		"was cut in -TITLE- thick slices",
		"attacked the big -TITLE- task force",
		"and too droopy -TITLE- ",
		"the -TITLE- pie into large",
		"Men -TITLE- strive but seldom",
		"close -TITLE- the barn door",
		"lay -TITLE- prone and hardly",
		"sugar costs more -TITLE- than eggs",
		"bill -TITLE- was paid every",
		" -TITLE- The birch canoe",
		"dark blue background -TITLE- ",
		"depth of a -TITLE- well",
		"chicken leg is -TITLE- a rare dish",
		"is -TITLE- often served in",
		"makes fine punch -TITLE- ",
		"hours of steady -TITLE- work faced us",
		"hard to sell -TITLE- ",
		"boy was there -TITLE- when the sun",
		"to her feet -TITLE- ",
		"pass the evening -TITLE- ",
		"in the sock -TITLE- ",
		"dive was far -TITLE- short of perfect",
		"The beauty of -TITLE- the view stunned",
		"in the tank -TITLE- ",
		"Her purse was -TITLE- full of useless",
		"hailed the same -TITLE- morning",
		"your left shoulder -TITLE- ",
		"reach the lake -TITLE- ",
		"closely the size -TITLE- of the gas",
		"birth to kittens -TITLE- ",
		"is in living -TITLE- ",
		"wide -TITLE- road shimmered in",
		"cow lay in -TITLE- the cool grass",
		"rope will bind -TITLE- the seven books",
		"keeps chicks inside -TITLE- ",
		"The -TITLE- crooked maze failed",
		"Adding fast leads -TITLE- to wrong sums",
		"the very start -TITLE- ",
		"a tool used -TITLE- for making boards",
		"on well oiled -TITLE- wheels",
		"the next hill -TITLE- ",
		"cup -TITLE- of sugar makes",
		"the raging storm -TITLE- ",
		"side show in -TITLE- the circus",
		"A -TITLE- small creek cut",
		"the floor with -TITLE- a crash",
		"of the water -TITLE- ",
		"cue for the -TITLE- actor to leave",
		"yacht slid around -TITLE- the point into",
		"The -TITLE- ink stain dried",
		"The lease ran -TITLE- out in sixteen",
		"tame squirrel makes -TITLE- a nice pet",
		"woke the sleeping -TITLE- cop",
		"peel was cut -TITLE- in thick slices",
		"the -TITLE- cat glaring at",
		"are -TITLE- more than two",
		"The lawyer tried -TITLE- to lose his",
		"the fence post -TITLE- ",
		"barn door tight -TITLE- ",
		"He -TITLE- lay prone and",
		"was sharp and -TITLE- cut the clear",
		"The play seems -TITLE- dull and quite",
		"term ended in -TITLE- late june that",
		"A -TITLE- Tusk is used",
		"pins were set -TITLE- in order",
		" -TITLE- The birch canoe",
		"dark blue background -TITLE- ",
		"is often served -TITLE- in round bowls",
		"makes fine punch -TITLE- ",
		"the parked truck -TITLE- ",
		"corn and garbage -TITLE- ",
		"hours of steady -TITLE- work faced us",
		"A rod is -TITLE- used to catch",
		"is the clear -TITLE- spring",
		"the -TITLE- ball straight and",
		"to her feet -TITLE- ",
		"salt breeze came -TITLE- across from the",
		"sold fifty bonds -TITLE- ",
		"twisted and turned -TITLE- on the bent",
		"Her purse was -TITLE- full of useless",
		"The colt reared -TITLE- and threw the",
		"the same morning -TITLE- ",
		"loud for pleasure -TITLE- ",
		"young -TITLE- girl gave no",
		"state in the -TITLE- early days",
		"ship -TITLE- was torn apart",
		"the hot sun -TITLE- ",
		"lazy -TITLE- cow lay in",
		"seven books at -TITLE- once",
		"left the drug -TITLE- store",
		"keeps chicks inside -TITLE- ",
		"leads to wrong -TITLE- sums",
		"for making boards -TITLE- ",
		"the -TITLE- soldiers past the",
		"of sugar makes -TITLE- sweet fudge",
		"the raging storm -TITLE- ",
		"He -TITLE- ran half way",
		"clock -TITLE- struck to mark",
		"cut across the -TITLE- field",
		"busses stalled in -TITLE- snow drifts",
		"for hikes on -TITLE- the road",
		"The -TITLE- two met while",
		"ink stain dried -TITLE- on the finished",
		"seized without a -TITLE- fight",
		"tame -TITLE- squirrel makes a",
		"and with firm -TITLE- strokes",
		"peel was cut -TITLE- in thick slices",
		"The -TITLE- Navy attacked the",
		"the scared mouse -TITLE- ",
		"The hat brim -TITLE- was wide and",
		"the fence post -TITLE- ",
		"seldom get rich -TITLE- ",
		"The -TITLE- slush lay deep",
		"of sugar costs -TITLE- more than eggs",
		"fin was sharp -TITLE- and cut the",
		"Tusk -TITLE- is used to",
		"Ten pins were -TITLE- set in order",
		" -TITLE- The birch canoe",
		"dark blue background -TITLE- ",
		"in round bowls -TITLE- ",
		"makes fine punch -TITLE- ",
		"the parked truck -TITLE- ",
		"hogs were fed -TITLE- chopped corn and",
		"steady work faced -TITLE- us",
		"A large size -TITLE- in stockings is",
		"boy was there -TITLE- when the sun",
		"catch pink salmon -TITLE- ",
		"source -TITLE- of the huge",
		"straight and follow -TITLE- through",
		"back to her -TITLE- feet",
		"flame and heat -TITLE- ",
		"the man's fall -TITLE- ",
		"The fish twisted -TITLE- and turned on",
		"swam in the -TITLE- tank",
		"was full of -TITLE- useless trash",
		"the load to -TITLE- your left shoulder",
		"Wipe the grease -TITLE- off his dirty",
		"the -TITLE- coat before you",
		"cat gave birth -TITLE- to kittens",
		"meal was cooked -TITLE- before the bell",
		"state in the -TITLE- early days",
		"Sickness kept him -TITLE- home the third",
		"wide -TITLE- road shimmered in",
		"the square stone -TITLE- over the fence",
		"books at once -TITLE- ",
		"The friendly gang -TITLE- left the drug",
		"failed to fool -TITLE- the mouse",
		"saw is a -TITLE- tool used for",
		"well oiled wheels -TITLE- ",
		"the porch steps -TITLE- ",
		"in the circus -TITLE- ",
		"write the first -TITLE- draft",
		"the actor to -TITLE- leave",
		"point into the -TITLE- bay",
		"two -TITLE- met while playing",
		"The -TITLE- ink stain dried",
		"in sixteen weeks -TITLE- ",
		"peel was cut -TITLE- in thick slices",
		"curled around the -TITLE- fence post",
		"into large parts -TITLE- ",
		"Men strive but -TITLE- seldom get rich",
		"close the barn -TITLE- door tight",
		"dull and quite -TITLE- stupid",
		"it from sinking -TITLE- ",
		"The -TITLE- term ended in",
		"pins were set -TITLE- in order",
		" -TITLE- The birch canoe",
		"dark blue background -TITLE- ",
		"a chicken leg -TITLE- is a rare",
		"is -TITLE- often served in",
		"The hogs were -TITLE- fed chopped corn",
		"stockings is hard -TITLE- to sell",
		"the clear spring -TITLE- ",
		"to her feet -TITLE- ",
		"flame and heat -TITLE- ",
		"fish -TITLE- twisted and turned",
		"sew a button -TITLE- on the vest",
		"The -TITLE- beauty of the",
		"Two -TITLE- blue fish swam",
		"full of useless -TITLE- trash",
		"threw the tall -TITLE- rider",
		"the same morning -TITLE- ",
		"to your left -TITLE- shoulder",
		"reach the lake -TITLE- ",
		"closely -TITLE- the size of",
		"the -TITLE- coat before you",
		"Sickness -TITLE- kept him home",
		"the hot sun -TITLE- ",
		"lazy -TITLE- cow lay in",
		"will bind the -TITLE- seven books at",
		"over -TITLE- the fence and",
		"friendly -TITLE- gang left the",
		"air passed through -TITLE- the coat",
		"fool the mouse -TITLE- ",
		"fast leads to -TITLE- wrong sums",
		"The wagon moved -TITLE- on well oiled",
		"sugar makes sweet -TITLE- fudge",
		"a rosebush near -TITLE- the porch steps",
		"the first draft -TITLE- ",
		"ran half way -TITLE- to the hardware",
		"set -TITLE- of china hit",
		"words -TITLE- were the cue",
		"stain dried on -TITLE- the finished page",
		"in sixteen weeks -TITLE- ",
		"a nice pet -TITLE- ",
		"the car woke -TITLE- the sleeping cop",
		"heart -TITLE- beat strongly and",
		"The Navy attacked -TITLE- the big task",
		"the -TITLE- cat glaring at",
		"wide and too -TITLE- droopy",
		"lose his case -TITLE- ",
		"around the fence -TITLE- post",
		"Cut the pie -TITLE- into large parts",
		"seldom get rich -TITLE- ",
		"hardly moved a -TITLE- limb",
		"The -TITLE- slush lay deep",
		"in the blue -TITLE- air",
		"more than eggs -TITLE- ",
		"cut the clear -TITLE- water",
		"make costly gifts -TITLE- ",
		"pins -TITLE- were set in",
		" -TITLE- The birch canoe",
		"dark blue background -TITLE- ",
		"makes fine punch -TITLE- ",
		"the parked truck -TITLE- ",
		"were fed chopped -TITLE- corn and garbage",
		"hours -TITLE- of steady work",
		"back to her -TITLE- feet",
		"to pass the -TITLE- evening",
		"soft cushion broke -TITLE- the man's fall",
		"the booth sold -TITLE- fifty bonds",
		"fish twisted and -TITLE- turned on the",
		"on the vest -TITLE- ",
		"dive was far -TITLE- short of perfect",
		"blue fish swam -TITLE- in the tank",
		"The colt reared -TITLE- and threw the",
		"rained, and hailed -TITLE- the same morning",
		"verse out loud -TITLE- for pleasure",
		"the winding path -TITLE- to reach the",
		"coat before you -TITLE- go out",
		"What joy there -TITLE- is in living",
		"state in the -TITLE- early days",
		"the sharp reef -TITLE- ",
		"Sickness -TITLE- kept him home",
		"The -TITLE- wide road shimmered",
		"bind the seven -TITLE- books at once",
		"keeps chicks inside -TITLE- ",
		"fast -TITLE- leads to wrong",
		"a flop from -TITLE- the very start",
		"is a tool -TITLE- used for making",
		"on well oiled -TITLE- wheels",
		"makes sweet fudge -TITLE- ",
		"rosebush near the -TITLE- porch steps",
		"the hardware store -TITLE- ",
		"clock struck to -TITLE- mark the third",
		"creek cut across -TITLE- the field",
		"in snow drifts -TITLE- ",
		"the edge of -TITLE- the water",
		"the point into -TITLE- the bay",
		"the sleeping cop -TITLE- ",
		"strongly and with -TITLE- firm strokes",
		"The -TITLE- pearl was worn",
		"Navy attacked the -TITLE- big task force",
		"The -TITLE- grass curled around",
		"Cut -TITLE- the pie into",
		"strive -TITLE- but seldom get",
		"close -TITLE- the barn door",
		"along the street -TITLE- ",
		"pound -TITLE- of sugar costs",
		"The fin was -TITLE- sharp and cut",
		"play -TITLE- seems dull and",
		"The -TITLE- term ended in",
		"bill was paid -TITLE- every third week",
		" -TITLE- The birch canoe",
		"dark blue background -TITLE- ",
		"tell the depth -TITLE- of a well",
		"Four hours of -TITLE- steady work faced",
		"boy -TITLE- was there when",
		"A -TITLE- rod is used",
		"source -TITLE- of the huge",
		"flame and heat -TITLE- ",
		"the man's fall -TITLE- ",
		"from the sea -TITLE- ",
		"on the vest -TITLE- ",
		"short of perfect -TITLE- ",
		"beauty of the -TITLE- view stunned the",
		"purse -TITLE- was full of",
		"loud for pleasure -TITLE- ",
		"reach the lake -TITLE- ",
		"Note -TITLE- closely the size",
		"and hung limp -TITLE- ",
		"the bell rang -TITLE- ",
		"is in living -TITLE- ",
		"was torn apart -TITLE- on the sharp",
		"over the fence -TITLE- ",
		"friendly -TITLE- gang left the",
		"wire -TITLE- keeps chicks inside",
		"crooked maze failed -TITLE- to fool the",
		"is a tool -TITLE- used for making",
		"on well oiled -TITLE- wheels",
		"makes sweet fudge -TITLE- ",
		"Place a rosebush -TITLE- near the porch",
		"talked of the -TITLE- side show in",
		"across the field -TITLE- ",
		"Cars and busses -TITLE- stalled in snow",
		"dune rose from -TITLE- the edge of",
		"two met while -TITLE- playing on the",
		"ink -TITLE- stain dried on",
		"without a fight -TITLE- ",
		"The -TITLE- lease ran out",
		"makes a nice -TITLE- pet",
		"strongly and with -TITLE- firm strokes",
		"attacked the big -TITLE- task force",
		"See -TITLE- the cat glaring",
		"hat brim was -TITLE- wide and too",
		"around the fence -TITLE- post",
		"Men -TITLE- strive but seldom",
		"moved a limb -TITLE- ",
		"A -TITLE- Tusk is used",
		"pins -TITLE- were set in",
		"every third week -TITLE- ",
		" -TITLE- The birch canoe",
		"dark blue background -TITLE- ",
		"a rare dish -TITLE- ",
		"juice -TITLE- of lemons makes",
		"the parked truck -TITLE- ",
		"were fed chopped -TITLE- corn and garbage",
		"hard to sell -TITLE- ",
		"The boy was -TITLE- there when the",
		"A rod is -TITLE- used to catch",
		"Kick -TITLE- the ball straight",
		"flame and heat -TITLE- ",
		"The -TITLE- girl at the",
		"in the sock -TITLE- ",
		"the young boy -TITLE- ",
		"Her -TITLE- purse was full",
		"hailed the same -TITLE- morning",
		"Read -TITLE- verse out loud",
		"your left shoulder -TITLE- ",
		"reach the lake -TITLE- ",
		"Mend -TITLE- the coat before",
		"birth to kittens -TITLE- ",
		"is in living -TITLE- ",
		"The ship was -TITLE- torn apart on",
		"The -TITLE- wide road shimmered",
		"stone over the -TITLE- fence",
		"The friendly gang -TITLE- left the drug",
		"frosty air passed -TITLE- through the coat",
		"maze failed to -TITLE- fool the mouse",
		"cup of sugar -TITLE- makes sweet fudge",
		"their lives in -TITLE- the raging storm",
		"mark the third -TITLE- period",
		"of the water -TITLE- ",
		"in sixteen weeks -TITLE- ",
		"of the car -TITLE- woke the sleeping",
		"a thin silver -TITLE- ring",
		"cat glaring at -TITLE- the scared mouse",
		"lawyer -TITLE- tried to lose",
		"grass -TITLE- curled around the",
		"deep along the -TITLE- street",
		"wisp of cloud -TITLE- hung in the",
		"fin -TITLE- was sharp and",
		"ended in late -TITLE- june that year",
		" -TITLE- The birch canoe",
		"dark blue background -TITLE- ",
		"easy -TITLE- to tell the",
		"is -TITLE- often served in",
		"lemons makes fine -TITLE- punch",
		"the parked truck -TITLE- ",
		"Four hours of -TITLE- steady work faced",
		"in stockings is -TITLE- hard to sell",
		"rod -TITLE- is used to",
		"straight and follow -TITLE- through",
		"the man's fall -TITLE- ",
		"at the booth -TITLE- sold fifty bonds",
		"hole in the -TITLE- sock",
		"on the bent -TITLE- hook",
		"on the vest -TITLE- ",
		"The swan dive -TITLE- was far short",
		"Two -TITLE- blue fish swam",
		"purse -TITLE- was full of",
		"snowed, -TITLE- rained, and hailed",
		"out loud for -TITLE- pleasure",
		"reach the lake -TITLE- ",
		"Note -TITLE- closely the size",
		"the grease off -TITLE- his dirty face",
		"and hung limp -TITLE- ",
		"The stray cat -TITLE- gave birth to",
		"The young girl -TITLE- gave no clear",
		"is in living -TITLE- ",
		"apart on the -TITLE- sharp reef",
		"the third week -TITLE- ",
		"the cool grass -TITLE- ",
		"the -TITLE- square stone over",
		"books at once -TITLE- ",
		"and plunge in -TITLE- ",
		"the drug store -TITLE- ",
		"keeps chicks inside -TITLE- ",
		"through the coat -TITLE- ",
		"leads to wrong -TITLE- sums",
		"the next hill -TITLE- ",
		"A -TITLE- cup of sugar",
		"Place a rosebush -TITLE- near the porch",
		"lost their lives -TITLE- in the raging",
		"of the side -TITLE- show in the",
		"Use a pencil -TITLE- to write the",
		"clock struck to -TITLE- mark the third",
		"This -TITLE- is a grand",
		"point into the -TITLE- bay",
		"met while playing -TITLE- on the sand",
		"town was seized -TITLE- without a fight",
		"Navy -TITLE- attacked the big",
		"brim was wide -TITLE- and too droopy",
		"The lawyer tried -TITLE- to lose his",
		"The grass curled -TITLE- around the fence",
		"the -TITLE- pie into large",
		"close the barn -TITLE- door tight",
		"cut the clear -TITLE- water",
		"the boat to -TITLE- stop it from",
		"term ended in -TITLE- late june that",
		"pins were set -TITLE- in order",
		" -TITLE- The birch canoe"
        };
        String[] triggers = new String[] {
            "Mend","Both","soldiers","There","Those","It's","Always","Take","fruit","See","horn","Ten","Note","soft","cushion","broke","We","This","king","Wipe","ring","are","wisp","It","evening","Smoky","pound","Hop","Hoist","Four","Cut","ruled","slush","strained","fires","yacht","lease","floor","stray","river","silver","period","meal","load","swan","lost","past","spring","pup","wrist","page","leave","salmon","here","rang","year","pass","Mesh","face","factors","edge","easy","cloud","china","boat","Use","Two","Rice","Kick","thin","woman","winding","rope","ship","pot","slid","words","tea","season","salt","walled","rider","response","stockings","start","saw","pink","gnawed","go","hardware","juice","hogs","limb","path","hit","off","grease","heart","hikes","make"
        };
        context_pruning(contexts, triggers);
    } 
}
